/// An immutable configuration store.
interface store {
    /// Gets a configuration value of type `string` associated with the `key`. 
    ///
    /// Returns `none` if the key does not exist.
    ///
    /// This always returns the same value for any given key. Configuration
    /// data does not change over the lifetime of the component instance.
    get: func(
        /// A string key to fetch
        key: string
    ) -> option<string>;

    /// Gets a list of configuration key-value pairs of type `string`.
    ///
    /// This always returns the same data. Configuration data does not change
    /// over the lifetime of the component instance.
    get-all: func() -> list<tuple<string, string>>;
}
